name: Build and Push Docker Images

on:
  push:
    branches:
      - main
    paths:
      - 'daemon.Dockerfile'
      - 'web.Dockerfile'
      - '.github/workflows/docker-build.yml'
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: lirzh/armhf-mcsm
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha
      
      - name: Build and push daemon image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./daemon.Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }},lirzh/armhf-mcsm:daemon
          labels: ${{ steps.meta.outputs.labels }}
      
      - name: Build and push web image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./web.Dockerfile
          platforms: linux/arm/v7
          push: true
          tags: ${{ steps.meta.outputs.tags }},lirzh/armhf-mcsm:web
          labels: ${{ steps.meta.outputs.labels }}