name: Sync MCSManager

on:
  schedule:
    - cron: '0 * * * *'  # 每小时执行一次
  workflow_dispatch:      # 允许手动触发

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          submodules: true

      - name: Sync MCSManager
        run: |
          # 配置 Git 用户信息
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # 添加 MCSManager 作为子模块
          git submodule add https://github.com/MCSManager/MCSManager.git MCSM || echo "Submodule already exists"
          
          # 初始化并更新子模块
          git submodule init
          git submodule update
          
          # 提交更改
          git add .
          git commit -m "Sync MCSManager to MCSM folder" || echo "No changes to commit"
          
          # 推送更改
          git push